name: "Build Nix package"
on:
    push:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2.0.0
        - uses: cachix/install-nix-action@v12
        - run: nix-build
