name: "Build Nix package"
on:
    push:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3.0.2
        - uses: cachix/install-nix-action@v12
        - uses: cachix/cachix-action@v8
          with:
              name: moosingin3space
              authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
        - run: nix-build
